---
title: "Untitled"
author: "Marcelo"
date: "November 12, 2016"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



## R Markdown

\begin{equation}
\min_{q}\sum_{t=1}^{n}\alpha|y_{t}-q(x_t)|^{+}+(1-\alpha)|y_{t}-q(x_t)|^{-},
\label{eq:linear-model}
\end{equation}
where $q(x_t)$ is the estimated quantile value at a given time $t$ and $|x|^+=\max\{0,x\}$ and $|x|^-=-\min\{0,x\}$. To model this problem as a Linear Programming problem, thus being able to use a modern solver to fit our model,  we can create variables $\varepsilon^+_t$ e $\varepsilon^-_t$ to represent $|y-q(x_t)|^+$ and $|y-q(x_t)|^-$, respectively. So we have:
\begin{equation}
\begin{aligned}\min_{q,\varepsilon_{t}^{+}, \varepsilon_{t}^{-}} & \sum_{t=1}^{n}\left(\lambda\varepsilon_{t}^{+}+(1-\lambda)\varepsilon_{t}^{-}\right) & \\
\mbox{s.t. } & \varepsilon_{t}^{+}-\varepsilon_{t}^{-}=y_{t}-q(x_{t}), & \qquad\forall t \in \{1,\dots,n\},\\
& \varepsilon_t^+,\varepsilon_t^- \geq 0, & \qquad \forall t \in \{1,\dots,n\}.
\end{aligned}
\label{eq:qar-general}
\end{equation}


## Probabilistic Forecast of Wind Power

In this approach, we find an approximation for the forecasted variable density $\hat{f}_{t+k|t}$ by estimating a range of $m$ quantile forecasts:

$$\hat{f}_{t+k|t} = \{  \hat{q}^{(\alpha_i)}_{t+k|t} | 0 \leq \alpha_1 \leq \dots \leq \alpha_i \leq \alpha_m leq 1 \}$$

